[template]
src = "update.sh.tmpl"
dest = "/usr/local/bin/update.sh"
mode = "755"
keys = [
    "/hosts",
    "/services",
    "/containers",
    "/services/${GRAPHITE_SERVICE}/containers/0/hostname",
]
